import pathlib
import sys
import math

import bpy
from mathutils import Matrix


ROOT = pathlib.Path(__file__).resolve().parents[2]
ASSETS = ROOT / "src" / "resources" / "assets" / "wartecmod"
MODEL_OUT = ASSETS / "models" / "strategic"
TEXTURE_OUT = ASSETS / "textures" / "models" / "strategic"


def reset_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for collection in (bpy.data.meshes, bpy.data.curves, bpy.data.materials,
                       bpy.data.images):
        for value in list(collection):
            collection.remove(value)


def import_glb(path):
    bpy.ops.import_scene.gltf(filepath=str(path))


def meshes():
    return [value for value in bpy.context.scene.objects if value.type == "MESH"]


def remove_non_meshes_and_named_fragments(fragments, exact_names=()):
    for value in list(bpy.context.scene.objects):
        lowered = value.name.lower()
        if (value.type != "MESH" or lowered in exact_names
                or any(fragment in lowered for fragment in fragments)):
            bpy.data.objects.remove(value, do_unlink=True)


def bake_world_transforms():
    """Flatten the complete glTF parent hierarchy into every mesh."""
    for value in meshes():
        # Imported glTF nodes commonly share mesh data. Copy it before applying
        # the object's world matrix so one instance cannot deform another.
        value.data = value.data.copy()
        world = value.matrix_world.copy()
        value.parent = None
        value.matrix_world = Matrix.Identity(4)
        value.data.transform(world)
        value.data.update()


def mark_tu95_materials():
    glass = next((value for value in meshes()
                  if value.name.lower().startswith("camlar")), None)
    if glass is not None:
        for material in glass.data.materials:
            if material is not None:
                material.name = "wartech_tu95_glass"


def decimate_each(ratio, preserve=(), preserve_ratio=None):
    for value in meshes():
        is_detail = any(fragment in value.name.lower() for fragment in preserve)
        if len(value.data.polygons) < 160:
            continue
        bpy.context.view_layer.objects.active = value
        value.select_set(True)
        modifier = value.modifiers.new(name="wartech_lod", type="DECIMATE")
        modifier.ratio = (preserve_ratio if is_detail
                          and preserve_ratio is not None else ratio)
        modifier.use_collapse_triangulate = True
        bpy.ops.object.modifier_apply(modifier=modifier.name)
        value.select_set(False)


def join_meshes(name):
    values = meshes()
    if not values:
        raise RuntimeError("Model contains no usable meshes")
    bpy.ops.object.select_all(action="DESELECT")
    for value in values:
        value.select_set(True)
    bpy.context.view_layer.objects.active = values[0]
    bpy.ops.object.join()
    result = bpy.context.object
    result.name = name
    result.data.name = name
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    for polygon in result.data.polygons:
        polygon.use_smooth = True
    # Forge 1.7.10's OBJ loader is unstable with the separate custom-normal
    # index stream generated by Blender's Weighted Normal modifier. Keep the
    # mesh's regular vertex normals; the exporter below deliberately omits vn.
    result.data.use_auto_smooth = False
    return result


def tag_tu95_parts():
    """Split the aircraft into Forge-safe display-list sized sections."""
    rotor_sources = {
        "cone.002": ("prop_outer_left_front", "prop_outer_right_front"),
        "cone.003": ("prop_outer_left_rear", "prop_outer_right_rear"),
        "cone.006": ("prop_inner_left_front", "prop_inner_right_front"),
        "cone.007": ("prop_inner_left_rear", "prop_inner_right_rear"),
    }
    tagged = []
    airframe_groups = []
    for value in meshes():
        key = next((name for name in rotor_sources
                    if value.name.lower().startswith(name)), None)
        if key is not None:
            left_name, right_name = rotor_sources[key]
            left = value.vertex_groups.new(name=left_name)
            right = value.vertex_groups.new(name=right_name)
            left_indices = [vertex.index for vertex in value.data.vertices
                            if vertex.co.x < 0.0]
            right_indices = [vertex.index for vertex in value.data.vertices
                             if vertex.co.x >= 0.0]
            left.add(left_indices, 1.0, "REPLACE")
            right.add(right_indices, 1.0, "REPLACE")
            tagged.extend((left_name, right_name))
            continue

        lowered = value.name.lower()
        wing_sources = ("circle.001", "circle.002", "circle.004", "circle.005",
                        "circle.006", "circle.008")
        gear_sources = ("circle_", "circle.007", "circle.009", "cube.003",
                        "cylinder_0")
        if lowered.startswith(wing_sources):
            group_name = "airframe_wings"
        elif lowered.startswith(gear_sources):
            group_name = "airframe_gear"
        elif (lowered.startswith("camlar") or lowered.startswith("circle.010")
              or len(value.data.polygons) < 300):
            group_name = "airframe_details"
        else:
            continue
        group = value.vertex_groups.new(name=group_name)
        group.add([vertex.index for vertex in value.data.vertices], 1.0, "REPLACE")
        if group_name not in airframe_groups:
            airframe_groups.append(group_name)
    if len(tagged) != 8:
        raise RuntimeError("Expected eight Tu-95 rotor groups, found %d" % len(tagged))
    return airframe_groups + tagged


def separate_vertex_group(model, group_name):
    bpy.ops.object.select_all(action="DESELECT")
    model.select_set(True)
    bpy.context.view_layer.objects.active = model
    group = model.vertex_groups.get(group_name)
    if group is None:
        raise RuntimeError("Missing rotor group " + group_name)
    before = set(bpy.context.scene.objects)
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="DESELECT")
    bpy.ops.object.vertex_group_set_active(group=group_name)
    bpy.ops.object.vertex_group_select()
    bpy.ops.mesh.separate(type="SELECTED")
    bpy.ops.object.mode_set(mode="OBJECT")
    created = [value for value in bpy.context.scene.objects if value not in before]
    if len(created) != 1:
        raise RuntimeError("Could not separate rotor group " + group_name)
    part = created[0]
    part.name = group_name
    part.data.name = group_name
    return part


def split_tu95_parts(model, group_names):
    parts = []
    for group_name in group_names:
        parts.append(separate_vertex_group(model, group_name))
    model.name = "body"
    model.data.name = "body"
    for part in [model] + parts:
        for polygon in part.data.polygons:
            polygon.use_smooth = True
    return [model] + parts


def normalize(model, target_length):
    coordinates = [model.matrix_world @ vertex.co for vertex in model.data.vertices]
    minimum = [min(value[index] for value in coordinates) for index in range(3)]
    maximum = [max(value[index] for value in coordinates) for index in range(3)]
    dimensions = [maximum[index] - minimum[index] for index in range(3)]
    horizontal_length = max(dimensions[0], dimensions[1])
    scale = target_length / max(0.001, horizontal_length)
    model.scale = (scale, scale, scale)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    coordinates = [model.matrix_world @ vertex.co for vertex in model.data.vertices]
    minimum = [min(value[index] for value in coordinates) for index in range(3)]
    maximum = [max(value[index] for value in coordinates) for index in range(3)]
    model.location.x -= (minimum[0] + maximum[0]) * 0.5
    model.location.y -= (minimum[1] + maximum[1]) * 0.5
    model.location.z -= minimum[2]
    bpy.ops.object.transform_apply(location=True, rotation=False, scale=False)


def bake_atlas(model, name, size, gamma):
    bpy.context.view_layer.objects.active = model
    model.select_set(True)
    source_uv = model.data.uv_layers.active
    if source_uv is None:
        source_uv = model.data.uv_layers.new(name="SourceUV")
    source_uv_name = source_uv.name
    # Adding another UV layer can invalidate Blender's RNA collection proxy
    # after a Decimate modifier. Snapshot coordinates before creating it.
    source_uv_values = [(value.uv.x, value.uv.y) for value in source_uv.data]
    old_atlas = model.data.uv_layers.get("WarTechAtlas")
    if old_atlas is not None:
        model.data.uv_layers.remove(old_atlas)
    atlas_uv = model.data.uv_layers.new(name="WarTechAtlas")
    material_count = max(1, len(model.data.materials))
    grid = int(math.ceil(math.sqrt(material_count)))
    tile_padding = 0.018
    for polygon in model.data.polygons:
        tile = min(material_count - 1, max(0, polygon.material_index))
        tile_x = tile % grid
        tile_y = tile // grid
        for loop_index in polygon.loop_indices:
            source = source_uv_values[loop_index]
            local_u = max(0.0, min(1.0, source[0]))
            local_v = max(0.0, min(1.0, source[1]))
            local_u = tile_padding + local_u * (1.0 - tile_padding * 2.0)
            local_v = tile_padding + local_v * (1.0 - tile_padding * 2.0)
            atlas_uv.data[loop_index].uv = (
                (tile_x + local_u) / grid,
                (tile_y + local_v) / grid)
    model.data.uv_layers.active = atlas_uv
    atlas_uv.active_render = True

    atlas = bpy.data.images.new(name, width=size, height=size, alpha=True)
    atlas.generated_color = (0.56, 0.57, 0.60, 0.0)
    for material in model.data.materials:
        material.use_nodes = True
        nodes = material.node_tree.nodes
        links = material.node_tree.links
        # glTF image nodes without a Vector link follow the active UV layer.
        # Pin them to the source map before making the atlas active for bake.
        uv_node = nodes.new("ShaderNodeUVMap")
        uv_node.uv_map = source_uv_name
        for image_node in [node for node in nodes if node.type == "TEX_IMAGE"]:
            if not image_node.inputs["Vector"].is_linked:
                links.new(uv_node.outputs["UV"], image_node.inputs["Vector"])
        output = next((node for node in nodes
                       if node.type == "OUTPUT_MATERIAL"), None)
        if output is None:
            output = nodes.new("ShaderNodeOutputMaterial")
        principled = next((node for node in nodes
                           if node.type == "BSDF_PRINCIPLED"), None)
        emission = nodes.new("ShaderNodeEmission")
        # The source Tu-95 uses translucent white glass. Emission baking drops
        # that alpha and used to turn the cockpit into solid white fragments.
        glass_override = (name == "tu95_bear"
                          and material.name == "wartech_tu95_glass")
        if glass_override:
            emission.inputs["Color"].default_value = (0.035, 0.055, 0.07, 1.0)
        elif principled is not None:
            source = principled.inputs["Base Color"]
            if source.is_linked:
                color_output = source.links[0].from_socket
                if gamma != 1.0:
                    gamma_node = nodes.new("ShaderNodeGamma")
                    gamma_node.inputs["Gamma"].default_value = gamma
                    links.new(color_output, gamma_node.inputs["Color"])
                    color_output = gamma_node.outputs["Color"]
                links.new(color_output, emission.inputs["Color"])
            else:
                color = source.default_value
                emission.inputs["Color"].default_value = (
                    pow(color[0], gamma), pow(color[1], gamma),
                    pow(color[2], gamma), color[3])
        else:
            emission.inputs["Color"].default_value = material.diffuse_color
        for link in list(output.inputs["Surface"].links):
            links.remove(link)
        links.new(emission.outputs["Emission"], output.inputs["Surface"])

        node = material.node_tree.nodes.new("ShaderNodeTexImage")
        node.image = atlas
        material.node_tree.nodes.active = node
        node.select = True

    bpy.context.scene.render.engine = "CYCLES"
    bpy.context.scene.cycles.device = "CPU"
    bpy.context.scene.render.bake.use_clear = False
    bpy.context.scene.render.bake.margin = 16
    bpy.ops.object.bake(type="EMIT")
    pixels = list(atlas.pixels)
    for index in range(0, len(pixels), 4):
        if pixels[index + 3] < 0.5:
            pixels[index] = 0.56
            pixels[index + 1] = 0.57
            pixels[index + 2] = 0.60
            pixels[index + 3] = 1.0
    atlas.pixels[:] = pixels
    atlas.update()
    texture_path = TEXTURE_OUT / (name + ".png")
    texture_path.parent.mkdir(parents=True, exist_ok=True)
    atlas.filepath_raw = str(texture_path)
    atlas.file_format = "PNG"
    atlas.save()

    # Forge 1.7.10's OBJ loader must see one unambiguous UV set.
    for uv_name in [layer.name for layer in model.data.uv_layers
                    if layer.name != "WarTechAtlas"]:
        uv_layer = model.data.uv_layers.get(uv_name)
        if uv_layer is not None:
            model.data.uv_layers.remove(uv_layer)
    model.data.uv_layers.active = model.data.uv_layers["WarTechAtlas"]
    model.data.uv_layers["WarTechAtlas"].active_render = True

    material = bpy.data.materials.new(name + "_material")
    material.diffuse_color = (1.0, 1.0, 1.0, 1.0)
    model.data.materials.clear()
    model.data.materials.append(material)
    for polygon in model.data.polygons:
        polygon.material_index = 0


def export_obj(models, name):
    MODEL_OUT.mkdir(parents=True, exist_ok=True)
    bpy.ops.object.select_all(action="DESELECT")
    for model in models:
        model.select_set(True)
    bpy.context.view_layer.objects.active = models[0]
    bpy.ops.export_scene.obj(
        filepath=str(MODEL_OUT / (name + ".obj")),
        use_selection=True,
        use_materials=False,
        # Each part now stays well below the old loader's practical limits, so
        # preserve authored normals instead of forcing flat reconstructed ones.
        use_normals=True,
        use_uvs=True,
        use_triangles=True,
        use_mesh_modifiers=True,
        group_by_object=True,
        keep_vertex_order=True,
        axis_forward="-Z",
        axis_up="Y",
    )
    vertices = sum(len(model.data.vertices) for model in models)
    triangles = sum(sum(max(0, len(value.vertices) - 2)
                        for value in model.data.polygons) for model in models)
    print(name, "vertices", vertices, "triangles", triangles)
    for model in models:
        coordinates = [model.matrix_world @ vertex.co for vertex in model.data.vertices]
        minimum = [min(value[index] for value in coordinates) for index in range(3)]
        maximum = [max(value[index] for value in coordinates) for index in range(3)]
        center = [(minimum[index] + maximum[index]) * 0.5 for index in range(3)]
        print("part", model.name, "vertices", len(model.data.vertices),
              "center", tuple(round(value, 5) for value in center))


def process(source, name, target_length, decimation, atlas_size, remove=(),
            remove_exact=(), gamma=1.0, preserve=(), preserve_ratio=None,
            split_parts=None):
    reset_scene()
    import_glb(source)
    remove_non_meshes_and_named_fragments(remove, remove_exact)
    if name == "tu95_bear":
        mark_tu95_materials()
    bake_world_transforms()
    decimate_each(decimation, preserve, preserve_ratio)
    # Decimate rebuilds mesh topology, so tag animated parts afterwards.
    group_names = split_parts() if split_parts is not None else []
    model = join_meshes(name)
    normalize(model, target_length)
    bake_atlas(model, name, atlas_size, gamma)
    models = split_tu95_parts(model, group_names) if group_names else [model]
    export_obj(models, name)


def main():
    TEXTURE_OUT.mkdir(parents=True, exist_ok=True)
    process(
        ROOT / "models_inbox" / "tu" / "tu-95_bear.glb",
        "tu95_bear",
        42.0,
        # Spend geometry on the airframe silhouette and keep the eight rotor
        # parts individually cheap enough for Forge 1.7.10 display lists.
        0.68,
        2048,
        remove_exact=("cube", "cube.001_0", "cylinder.001_0"),
        gamma=0.90,
        preserve=("cone.002", "cone.003", "cone.006", "cone.007"),
        preserve_ratio=0.38,
        split_parts=tag_tu95_parts,
    )
    process(
        ROOT / "models_inbox" / "X-555"
        / "russian_x-555_air-launched_cruise_missile.glb",
        "kh555",
        5.9,
        0.32,
        512,
    )


if __name__ == "__main__":
    main()
